version: '3.3'

services:
  authentication_db:
    image: mysql:8.0
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: authdb
      MYSQL_USER: admin1
      MYSQL_PASSWORD: admin1
    volumes:
      - "./schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./data.sql:/docker-entrypoint-initdb.d/2.sql"
  authentication_service:
    depends_on:
      - authentication_db
    image: authentication-service:latest
    restart: always
    ports:
      - 8081:8081
    environment:
      JDBC_DATABASE_URL: jdbc:mysql://localhost:3306/authdb?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      JDBC_DATABASE_PASSWORD: admin1
      JDBC_DATABASE_USERNAME: admin1