version: '3.7'

services:
  authentication-service:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: khalld/authentication-service:latest
    # depends_on: # TODO: this will not be managed by docker-compose if db and service are in different stacks
    #   authentication-db:
    #     condition: service_healthy
    restart: unless-stopped
    ports:
      - 8082:8082
    environment:
      JDBC_DATABASE_URL: jdbc:mysql://authentication-db:3306/authdb?allowPublicKeyRetrieval=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      JDBC_DATABASE_PASSWORD: admin
      JDBC_DATABASE_USERNAME: admin
    networks:
      - authentication-network
      - authentication-db-network
    volumes:
      - maven_packages:/root/.m2
    container_name: authentication-service

networks: 
  authentication-network:
    name: authentication-network
  authentication-db-network:
    name: authentication-db-network
volumes:
  maven_packages:
    name: maven_packages